{ "data": [ { "id":899, "name":"BASE", "storeIds":[ 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 21, 22, 23, 347, 348, 356, 369, 373, 377 ] }, { "id":65699, "name":"V1", "storeIds":[ ] }, { "id":65700, "name":"V2", "storeIds":[ ] } ] , "success":true }